---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-selfsigned-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: {{ .Values.certmanager.secret }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-self
    kind: ClusterIssuer
    group: cert-manager.io