{{- if .Values.custom_resource.enabled }}
apiVersion: {{ .Values.custom_resource.apiVersion}}
kind: Keycloak
metadata:
  name: {{ .Values.custom_resource.name }}
  annotations:
  namespace: {{ .Release.Namespace }}
  labels:
   app: {{ .Values.custom_resource.name }}
spec:
  instances: {{ .Values.custom_resource.instances }}
  externalAccess:
    enabled: {{ .Values.custom_resource.externalAccess.enabled }}
    tlsTermination: "reencryp"
  externalDatabase:
    enabled: {{ .Values.custom_resource.externalDatabase.enabled }}
  keycloakDeploymentSpec:
    experimental:
      env:
      - name: DB_ADDR
        value: {{ .Values.keycloak_db.stringData.POSTGRES_EXTERNAL_ADDRESS}}
{{ end }}