apiVersion: v1
kind: Secret
metadata:
    name: keycloak-credentials
    namespace: {{ .Release.Namespace }}
data:
    {{- if .Release.IsInstall }}
    ADMIN_PASSWORD: {{ .Values.dbpassword | toString | b64enc }}
    {{ else }}
    ADMIN_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace "keycloak-credentials").data "ADMIN_PASSWORD" }} 
    {{ end }}
    ADMIN_USERNAME: {{ .Values.keycloakAdmin | toString | b64enc }}
type: Opaque