{{- if .Values.keycloak_db.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: {{ .Release.Namespace }}
stringData:
    POSTGRES_DATABASE: {{ quote .Values.keycloak_db.stringData.POSTGRES_DATABASE  }}
    POSTGRES_EXTERNAL_ADDRESS: {{ quote .Values.postgresAddress }}
    POSTGRES_ADDR: {{ quote .Values.postgresAddress }}
    POSTGRES_EXTERNAL_PORT: {{ quote .Values.keycloak_db.stringData.POSTGRES_EXTERNAL_PORT   }}
    {{- if .Release.IsInstall }}
    POSTGRES_PASSWORD: {{ quote .Values.dbpassword }}
    {{ else }}
    POSTGRES_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace "keycloak-db-secret").stringData "POSTGRES_PASSWORD" }}
    {{ end }}
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: {{ quote .Values.keycloak_db.stringData.POSTGRES_SUPERUSER   }}
    POSTGRES_USERNAME: {{ quote .Values.keycloak_db.stringData.POSTGRES_USERNAME   }}
type: Opaque
{{- end }}