{{- $name := printf "ngb.%s.credentials.postgresql.acid.zalan.do" .Values.clusterSvcName -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "ngb" | b64enc }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ .Values.dbpassword | toString | b64enc }}
  {{- end -}}