{{- if .Values.ingress.enabled }}
apiVersion: {{ .Values.ingress.tls_secret.apiVersion }}
kind: Secret
metadata:
  name: {{ .Values.ingress.tls_secret.name }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.ingress.tls_secret.tlsCrt | b64enc }}
  tls.key: {{ .Values.ingress.tls_secret.tlsKey | b64enc }}
type: kubernetes.io/tls
{{ end }}