apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ .Values.kafkaConnector.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnectConfig.name }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: "{{ .Values.kafkaConnector.hostname }}"
    database.port: "{{ .Values.kafkaConnector.port }}"
    database.user: "{{ .Values.kafkaConnector.username }}"
    database.password: "{{ .Values.kafkaConnector.password }}"
    database.dbname: "{{ .Values.kafkaConnector.dbname }}"
    database.server.name: "{{ .Values.kafkaConnector.server_name }}"
    database.history.kafka.bootstrap.servers: "{{ .Values.kafkaConnectConfig.bootstrapServer }}"
    database.history.kafka.topic: "schema-changes.entity"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"