apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafkaCluster.name }}
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: {{ .Values.kafkaCluster.storage.type }}
        size: {{ .Values.kafkaCluster.storage.size }}
        deleteClaim: false
  zookeeper:
    replicas: {{ .Values.kafkaCluster.zookeeper.replicas }}
    storage:
      type: {{ .Values.kafkaCluster.zookeeper.storage.type }}
      size: {{ .Values.kafkaCluster.zookeeper.storage.size }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}