apiVersion: v1
kind: Secret
metadata:
  name: ngb.{{ .Values.clusterSvcName }}.credentials.postgresql.acid.zalan.do
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "ngb" | b64enc }}
  password: {{ .Values.dbPassword | b64enc }}