{{- $name := printf "ngb.%s.credentials.postgresql.acid.zalan.do" .Values.clusterSvcName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "ngb" | b64enc }}
  {{- if .Release.IsInstall }}
  password: {{ .Values.dbpassword | toString | b64enc }}
  {{ else }}
  password: {{ index (lookup "v1" "Secret" .Release.Namespace $name).data "password" }}
  {{ end }}