apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: iff-minio-tenant
  namespace: {{ .Release.Namespace }}
spec:
  credsSecret:
    name: iff-creds-secret
  configuration:
    name: iff-configuration
  users:
    - name: minio-user
  pools:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi