{{- $secret := (lookup "v1" "Secret" .Release.Namespace "iff-configuration") -}}
apiVersion: v1
data:
  ## Tenant credentials, base64 encoded (cat config.env | base64)
  ##  export MINIO_ROOT_USER="minio"
  ##  export MINIO_ROOT_PASSWORD="minio123"
  ##  export MINIO_STORAGE_CLASS_STANDARD="EC:2"
  ##  export MINIO_BROWSER="on"
  {{- if $secret }}
  config.env: {{ index $secret.data "config.env" }}
  {{- else }}
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0ibWluaW8iCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJtaW5pbzEyMyIKZXhwb3J0IE1JTklPX1NUT1JBR0VfQ0xBU1NfU1RBTkRBUkQ9IkVDOjIiCmV4cG9ydCBNSU5JT19CUk9XU0VSPSJvbiI
  #{{printf "export MINIO_ROOT_USER=\"minio\";export MINIO_ROOT_PASSWORD=\"%s\";export MINIO_STORAGE_CLASS_STANDARD=\"EC:2\";export MINIO_BROWSER=\"on\"" (randAlphaNum 16) | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: iff-configuration
  namespace: {{ .Release.Namespace }}
type: Opaque