{{- $secret := (lookup "v1" "Secret" .Release.Namespace "minio-user") -}}
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: {{ "console2" | b64enc }}
  CONSOLE_SECRET_KEY: {{ "console123" | b64enc }}
kind: Secret
metadata:
  name: minio-user
  namespace: {{ .Release.Namespace }}
type: Opaque