{{- $name := printf "%s.%s.%s" .Values.db.dbUser .Values.clusterSvcName .Values.db.secretPostfix -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) -}}
apiVersion: v1
kind: Secret
metadata:
    name: alerta-db-secret
    namespace: {{ .Release.Namespace }}
data: 
    {{ if $secret }}
    {{- $alertaurl := printf "postgres://%s:%s@%s:5432/%s" .Values.db.dbUser (b64dec $secret.data.password) .Values.clusterSvcName .Values.db.alertaDb -}}
    DATABASE_URL: {{ $alertaurl | toString | b64enc }}
    {{ else }}
    {{-  $alertaurl := $name -}}
    {{/*{{- $alertaurl := printf "postgres://%s:%s@keycloak-postgresql:5432/%s"  .Values.db.dbUser .Values.dbpassword .Values.db.alertaDb -}}*/}}
    DATABASE_URL: {{ $alertaurl | toString | b64enc }}
    {{ end }}
type: Opaque