{{- if and .Values.adapter.enabled .Values.adapter.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Values.adapter.name }}-hpa
 namespace: {{ .Release.Namespace }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: {{ .Values.adapter.name }}
 minReplicas: {{ .Values.adapter.hpa.minReplicas }}
 maxReplicas: {{ .Values.adapter.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.adapter.hpa.targetCPUUtilizationPercentage }}
{{- end }}