{{- if .Values.adapter.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.adapter.name }}
  name: {{ .Values.adapter.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: {{ .Values.adapter.name }}
status: {}
{{- end }}