apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.keycloakClientSecrets }}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}