namespace: iff
ingressType: traefik # or nginx
keycloak:
  adminName: admin
  externalAuthService: keycloak.local  # put here the *external* keycloak name, i.e. through ingress
  internalAuthService: 
    name: keycloak-discovery
    port: 8080
db:
  teamId: acid
  clusterSvcPostfix: cluster
  pvSize: 1Gi
  podInstances: 2
certmanager:
  secret: selfsigned-cert-tls
  issuer: letsencrypt-self