environments:
  default:
    values:
    - default.yaml

releases:
- name: postgres
  chart: ./1-chart/charts/postgres
  namespace: {{ .Values.namespace }}
- name: kafka
  chart: ./1-chart/charts/kafka
  namespace: {{ .Values.namespace }}
- name: keycloak
  chart: ./1-chart/charts/keycloak
  namespace: {{ .Values.namespace }}
  needs:
  - postgres