environments:
  default:
    values:
    - default.yaml
    - templates.yaml.gotmpl

releases:
- name: postgres
  chart: ./1-chart/charts/postgres
  namespace: {{ .Values.namespace }}
  values:
  - dbpassword: {{ .Values.dbpassword }}
  - clusterSvcName: {{ .Values.db.teamId -}}-{{- .Values.db.clusterSvcPostfix }}
  - default.yaml
- name: kafka
  chart: ./1-chart/charts/kafka
  namespace: {{ .Values.namespace }}
- name: keycloak
  chart: ./1-chart/charts/keycloak
  namespace: {{ .Values.namespace }}
  values:
  - dbpassword: {{ .Values.dbpassword }}
  - default.yaml
  - postgresAddress: {{ .Values.db.teamId -}}-{{- .Values.db.clusterSvcPostfix -}}.{{- .Values.namespace -}}.svc.cluster.local

  needs:
  - postgres