apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.clusterSvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  teamId: {{ .Values.teamId }}
  volume:
    size: {{ .Values.pvSize }}
  numberOfInstances: {{ .Values.podInstances }}
  users:
{{ toYaml .Values.dbUsers | indent 4 }}
  databases:
{{ toYaml .Values.databases | indent 4 }}
  postgresql:
    version: "12"