keycloakOperator:
  keycloak_db:
   stringData:
    POSTGRES_EXTERNAL_ADDRESS: acid-minimal-cluster.digital-twin.svc.cluster.local
    POSTGRES_PASSWORD: postgres
  custom_resource:
   credentials:
    ADMIN_PASSWORD: admin
    ADMIN_USERNAME: admin
  keycloakAuthServer: http://keycloak-discovery:8080/auth
postgresOperator:
  teamId: acid
  # clusterSvcName: name must begin with "<teamId>-"
  clusterSvcName: acid-minimal-cluster
  dbPassword: postgres
strimzi:
  kafkaConnector:
    password: postgres
imageCredentials:
  username: 
  password: 
scorpioBroker:
  keycloak_vars:
    KEYCLOAK_SERVER_URL: http://keycloak-discovery:8080/auth
  keycloakClientSecrets:
    historyManagerSecret: notneeded
    entityManagerSecret: notneeded
    queryManagerSecret: notneeded
    subscriptionManagerSecret: notneeded
    registryManagerSecret: notneeded
