name: Docker Image CI

on:
  push:
    branches: [ flink-sql-operator-rebase-workflow ]
  pull_request:
    branches: [ flink-sql-operator-rebase-workflow ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: docker-compose build