name: Tag Image with Release Version

on:
  push:
    tags:
      - v*

jobs:
  push-release-images:
    runs-on: ubuntu-22.04
    env: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PREFIX: ${{ secrets.DOCKER_PREFIX }}
      SELF_HOSTED_RUNNER: true
    steps:
      - uses: actions/checkout@v2
      - name: Prepare K3d cluster
        run: |
          cd ./test && bash ./prepare-platform.sh
          java --version
      - name: Build Platform locally
        run: |
          exit 1
          cd test && bash build-local-platform.sh
      - name: Push release images
        shell: bash
        run: |
          exit 1
          set +o pipefail
          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
          TARGET_DOCKER_TAG=`git describe --tags --exact-match` || exit 1
          echo Selected tag ${TARGET_DOCKER_TAG}
          # Tag and push passed "k3d-iff.localhost:12345" with release tag
          docker images
          images=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep ":${TARGET_DOCKER_TAG}")
          echo I will push the following images: ${images}
          for image in $images; do
            newimage=$(echo $image | sed -r "s/k3d-iff.localhost:12345/docker.io/g");
            echo I will push image ${image} as ${newimage}
            docker tag ${image} ${newimage};
            docker push ${newimage};
          done
      - name: Setup upterm session
        if: failure()
        uses: lhotari/action-upterm@v1
