{{- if .Values.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiVersion}}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.issuer }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.certmanager.secret }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.ingress.serviceName }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: ImplementationSpecific
{{ end }}